<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <SpaRoot>..\kb.client</SpaRoot>
    <SpaProxyLaunchCommand>npm run dev</SpaProxyLaunchCommand>
    <SpaProxyServerUrl>https://localhost:59612</SpaProxyServerUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.AspNetCore.SpaProxy" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\kb.client\kb.client.esproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
    <ProjectReference Include="..\KB.Domain\KB.Domain.csproj" />
    <ProjectReference Include="..\KB.Core\KB.Core.csproj" />
    <ProjectReference Include="..\KB.Infrastructure\KB.Infrastructure.csproj" />
  </ItemGroup>

</Project>
