<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="Microsoft.SemanticKernel" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.AzureOpenAI" />

    <PackageReference Include="Microsoft.KernelMemory.Core" />
    <PackageReference Include="Microsoft.KernelMemory.AI.AzureOpenAI" />

    <PackageReference Include="Microsoft.KernelMemory.MemoryDb.Postgres" />
    <PackageReference Include="Microsoft.KernelMemory.DocumentStorage.AzureBlobs" />
    <PackageReference Include="Azure.Storage.Blobs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="AI\Prompts\*.txt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KB.Core\KB.Core.csproj" />
    <ProjectReference Include="..\KB.Domain\KB.Domain.csproj" />
  </ItemGroup>

</Project>
